### ISSUE TITLE
Colormap settings biAdvancedSettings

### ISSUE THREAD

**Issue by hhs2** [SAND-Lab/MEA-NAP#33]
biAdvancedSettings line 278
    network_plot_cmap_bounds.Z = [-2, 2];
There are no theoretical upper or lower bounds for Z score

**Comment by Timothysit** [comment]
I think `Params.use_theoretical_bounds` is perhaps a misnomer here: it is more of a custom / "default sensible" bound where most of the metrics are theoretical but yes Z-scores can be beyond this bound. It can't be removed because there needs to be a bound for each metric (if the user doesn't want to use the min and max of individual / across all recordings), so perhaps we should rename it to `Params.use_preset_bounds` or `Params.use_custom_bounds`? What do you think?

**Comment by Timothysit** [comment]
Renamed to `Params.use_custom_bounds` in this commit: ce5089f
