### ISSUE TITLE
Sample file running error

### ISSUE THREAD

**Issue by wxc1234567891111111** [SAND-Lab/MEA-NAP#51]
Hi，I downloaded the latest MEA-NAP code and also downloaded all the mat and CSV format files from the data package website you provided. However, when I imported the files into the MEApipeline GUI, the following error occurred. I want to know the reason for the error and what parameters I need to adjust to run it
![Snipaste_2024-05-23_11-17-27](https://github.com/SAND-Lab/MEA-NAP/assets/168263746/cecbb83b-45c4-4293-8451-f9e6345365ad)

**Comment by Timothysit** [comment]
Hi, thanks for trying out the pipeline! The error you saw is due to the selected sampling frequency (25 kHz by default) not matching the sampling frequency in the example file (12.5 kHz). I have just pushed an update so that the default parameters now work with the example file. You can read more about how to set the parameters [here](https://analysis-pipeline.readthedocs.io/en/latest/guide-for-new-users.html), and let me know if this fixes the issue, thanks!

**Comment by wxc1234567891111111** [comment]
Hello, thank you for your answer. The above issue has been resolved and I have successfully run it.
Additionally, we are using the MEA256 system, which outputs a. mcd file consisting of raw data from 262 channels. I would like to know if it is possible to use this MEApipeline to analyze the files output by the MEA256 system. How should I import the files into the pipeline?

**Comment by wxc1234567891111111** [comment]
![Uploading 262561c3-c385-4722-84a5-97e51d68059d.jpg…]()

**Comment by wxc1234567891111111** [comment]
![262561c3-c385-4722-84a5-97e51d68059d](https://github.com/SAND-Lab/MEA-NAP/assets/168263746/6b31314a-bb80-480c-8944-0106a177f9e3)

**Comment by wxc1234567891111111** [comment]
![Snipaste_2024-05-24_12-41-27](https://github.com/SAND-Lab/MEA-NAP/assets/168263746/3627c568-9761-49e8-aab3-97e4be222a53)

**Comment by Timothysit** [comment]
Yes, although we haven't tested the code on MEA256 systems, it is certainly possible to analyse these recordings with minor modifications to the code. First, you need to convert the .mcd files to .mat files, you should be able to do that by following the instructions [here](https://analysis-pipeline.readthedocs.io/en/latest/setting-up-meanap.html#convert-your-data-to-matlab-format-for-mea-nap). After the conversion, you can run the pipeline as normal, except in the layout settings, you need to select "custom" (since we currently do not provide a MEA256 layout, but that can certainly be done if needed), and specify your layout by editing the code [here](https://github.com/SAND-Lab/MEA-NAP/blob/2769696808ff6db556fa557125239a3a4f2678b1/Functions/getCoordsFromLayout.m#L2). Give it a go and let me know how it goes! I am also happy to add the MEA256 layout to the pipeline if you let me know how the channels are organised in that layout (from your screenshot I see letters and numbers, do you also have a mapping that go from channel number to x-y coordinates?)

**Comment by Timothysit** [comment]
Closing this for now, but feel free to re-open this issue if you or anyone else are interested in having MEA-NAP work with MEA256 systems.
