### ISSUE TITLE
Not enough nodes

### ISSUE THREAD

**Issue by adampavlinek** [SAND-Lab/MEA-NAP#53]
Hi I think I'm getting this message because I only have 16 electrodes per well:

I get the following message several times for each file: Not enough nodes to calculate network metrics! 

However at the end I also get an error:

Error using struct2table
Input structure is a scalar, but its
fields have different numbers of rows. If
you intended to create a table with one
row, set 'AsArray' to true.

Error in saveNetMet (line 153)
allRecordingLevelDataTable = struct2table(allRecordingLevelData);

Error in MEApipeline (line 451)
        saveNetMet(ExpName, Params, HomeDir)

**Comment by Timothysit** [comment]
Hi, can you go to debug mode in `saveNetMet.m` line 153, and let me know what is the value of  `allRecordingLevelData`? I suspect that because all the recordings have only 16 electrodes, it is struggling with making a table out of empty data. If you want to do some analysis on 16 electrodes, you can also adjust the minimum number of nodes required by modifying it in the GUI: you first toggle the advanced settings, then go into the advanced connectivity tab and reduce the minimum node number (set to 25 by default): 
![image](https://github.com/SAND-Lab/MEA-NAP/assets/11500169/2248d99f-a84a-45c3-834c-4122dd285771)

**Comment by Timothysit** [comment]
Hello! In the latest version of MEA-NAP (1.8.0 now), the pipeline automatically sets the minimum number of nodes to 16 for Axion16 recordings. Hopefully this fixes this issue, let me know if not and I will re-open this issue :)
